import { Header } from './components/layout/header'
import { ClientOnly } from './components/clientOnly'
import './globals.css'
import { Layout } from './components/layout'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientOnly>
          <Layout>
            { children }
          </Layout>  
        </ClientOnly>
      </body>
    </html>
  )
}
